### ISSUE TITLE
Dont know how to install

### ISSUE THREAD

**Issue by asturmas** [JackSlateur/perl-ip2as#1]
Hello,
We want use perl-ip2as with AS-Stats but dont know how to install the module on server and then configure then with ip2as::init('path/to/mapping.json');

Can you help please?

We have put the ip2as.pm in /usr/share/perl5/ and when try running your fork of AS-Stats  have this error:

`syntax error at /usr/share/perl5/ip2as.pm line 48, near "$data{"
Global symbol "$key" requires explicit package name at /usr/share/perl5/ip2as.pm line 49.
Global symbol "$key" requires explicit package name at /usr/share/perl5/ip2as.pm line 51.
Global symbol "$value" requires explicit package name at /usr/share/perl5/ip2as.pm line 51.
Global symbol "$key" requires explicit package name at /usr/share/perl5/ip2as.pm line 53.
Global symbol "$value" requires explicit package name at /usr/share/perl5/ip2as.pm line 53.
syntax error at /usr/share/perl5/ip2as.pm line 57, near "}"
syntax error at /usr/share/perl5/ip2as.pm line 63, near "}"
syntax error at /usr/share/perl5/ip2as.pm line 77, near "}"
Compilation failed in require at /data/as-stats/bin/asstatd.pl line 15.
BEGIN failed--compilation aborted at /data/as-stats/bin/asstatd.pl line 15.`

Thanks in advance,

**Comment by JackSlateur** [comment]
That's is wild
What perl version are you using ?
Are you sure your ip2as.pm file was not altered some way ?

Your overall procedure is correct : put the .pm in perl's PATH, then use AS-stats with -m <file.json>

**Comment by asturmas** [comment]
Hello,
We have donwload again the ip2as.pm and have some problem even with corrected command line:

```
syntax error at /usr/share/perl5/ip2as.pm line 48, near "$data{"
Global symbol "$key" requires explicit package name at /usr/share/perl5/ip2as.pm line 49.
Global symbol "$key" requires explicit package name at /usr/share/perl5/ip2as.pm line 51.
Global symbol "$value" requires explicit package name at /usr/share/perl5/ip2as.pm line 51.
Global symbol "$key" requires explicit package name at /usr/share/perl5/ip2as.pm line 53.
Global symbol "$value" requires explicit package name at /usr/share/perl5/ip2as.pm line 53.
syntax error at /usr/share/perl5/ip2as.pm line 57, near "}"
syntax error at /usr/share/perl5/ip2as.pm line 63, near "}"
syntax error at /usr/share/perl5/ip2as.pm line 77, near "}"
Compilation failed in require at /data/as-stats/bin/asstatd.pl line 15.
BEGIN failed--compilation aborted at /data/as-stats/bin/asstatd.pl line 15.
```

Im using **nohup /data/as-stats/bin/asstatd.pl -r /data/as-stats/rrd -k /data/as-stats/bin/knownlinks -m /usr/share/perl5/tools/ip2asn.json &** paths are correct.

Perl v5.10.1

Thanks,

**Comment by JackSlateur** [comment]
Perl 5.10 is really old, I confirm it does work with it

Perl 5.14 is too old too, 5.20 seems to be required (I'll update the README with that information)

Please, can you upgrade perl and try again ?

**Comment by asturmas** [comment]
Hello,
Its wired, we have upgrade perl and error its exactly the same. Im using centos 6.8.

`syntax error at /usr/share/perl5/ip2as.pm line 48, near "$data{"
Global symbol "$key" requires explicit package name at /usr/share/perl5/ip2as.pm line 49.
Global symbol "$key" requires explicit package name at /usr/share/perl5/ip2as.pm line 51.
Global symbol "$value" requires explicit package name at /usr/share/perl5/ip2as.pm line 51.
Global symbol "$key" requires explicit package name at /usr/share/perl5/ip2as.pm line 53.
Global symbol "$value" requires explicit package name at /usr/share/perl5/ip2as.pm line 53.
syntax error at /usr/share/perl5/ip2as.pm line 57, near "}"
syntax error at /usr/share/perl5/ip2as.pm line 63, near "}"
syntax error at /usr/share/perl5/ip2as.pm line 77, near "}"
Compilation failed in require at /data/as-stats/bin/asstatd.pl line 15.
BEGIN failed--compilation aborted at /data/as-stats/bin/asstatd.pl line 15.`

`perl -v

This is perl 5, version 24, subversion 1 (v5.24.1) built for x86_64-linux

Copyright 1987-2017, Larry Wall`

**Comment by JackSlateur** [comment]
Can you confirm that the following has no output ?
```
perl /path/to/ip2as.pm
```

**Comment by asturmas** [comment]
Yes, no output:

[root@flower ~]# perl /usr/share/perl5/ip2as.pm
[root@flower ~]#

**Comment by JackSlateur** [comment]
I don't know what happens
When you run perl /usr/share/perl5/ip2as.pm, no syntax error, which mean your perl version is correct
If you have syntax error when running asstatd.pl, that means you're still using the old version in that case

**Comment by adamgent** [comment]
Depending on how perl has been installed, you may find that asstatsd.pl is using /usr/bin/perl regardless of any other version.
Quite often /usr/bin/perl -v will say it's an older version that what "perl -v" does.

**Comment by zevlag** [comment]
Debian 7 wheezy still under LTS has version perl 5.14.2-21+deb7u2....

Doesn't work there...

**Comment by JackSlateur** [comment]
Please checkout, https://github.com/JackSlateur/perl-ip2as/commit/fd175450134077eab78e1839104d12ba20f45f41 should do the trick
