### ISSUE TITLE
Update ip2asn.json

### ISSUE THREAD

**Issue by rogallina** [JackSlateur/perl-ip2as#2]
Hi,

How do I update ip2asn.json ?

Thanks.

**Comment by JackSlateur** [comment]
Hi

The file used by tools/fetch_ip_asn.py is simply a list of ASN, one per line
It is made to be used by https://github.com/manuelkasper/AS-Stats/blob/master/www/asinfo.txt , but the first column is the only required part

If you want to create your own tool or whatever, ip2asn.json's format is simple:
```json
{
    "0.0.0.0/0": "15576",
    "1.0.128.0/17": "9737",
    "1.0.128.0/18": "9737",
    "1.0.128.0/19": "9737",
    "1.0.128.0/24": "23969",
    "1.0.129.0/24": "23969",
...
}
```

Basically, it is a simple mapping "subnet -> ASN" (v6 are supported indeed)
This mapping is used to create a radix tree, think of it as a routing table : you do not have to worry about overlaps

**Comment by rogallina** [comment]
Hi,

I do not know python.
My current version is 3.4.

running fetch_ip_asn.py

File "fetch_ip_asn.py", line 10
    print(f'Usage: {sys.argv[0]} <asinfo.txt>')
                                                                 ^
SyntaxError: invalid syntax

**Comment by JackSlateur** [comment]
Hi,

Yes, Python3.6 was required
I updated the code for you, it should now work for your version

I also made is multiprocessed

**Comment by rogallina** [comment]
Perfect.
Thanks.
