### ISSUE TITLE
Update ip2asn.json because 0.0.0.0/0 is included

### ISSUE THREAD

**Issue by barhom** [JackSlateur/perl-ip2as#3]
ASN15576 has the 0.0.0.0/0 range in the included ip2asn.json.
This should be removed.

**Comment by JackSlateur** [comment]
Hi,

I believe part of this issue is fixed (see 408d499b580bfda9abb3cdd13d5564bea86c55cb)
Please remember that the sample is based on RIPE, which is not a reliable source of truth (sadly)
